<%@ Page Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="CarModels.aspx.cs" Inherits="lab7.CarModels" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
        <br />
<table border="0">
    <tr>
    <td>
    <asp:Label ID="LabelFindCarModel" runat="server" Text="Название модели"></asp:Label><asp:TextBox ID="TextBoxFindCarModel" runat="server"></asp:TextBox>
        <asp:Button ID="ButtonFindCarModel" runat="server" Text="Найти" OnClick="ButtonFindCarModel_Click" />
    <br />        
        <asp:GridView ID="GridViewCarModel" runat="server" AutoGenerateColumns="False"
            AllowPaging="True" 
            AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" 
            OnRowCancelingEdit="GridViewCarModel_RowCancelingEdit" 
            OnRowDeleting="GridViewCarModel_RowDeleting" 
            OnRowEditing="GridViewCarModel_RowEditing" 
            OnRowUpdating="GridViewCarModel_RowUpdating" PageSize="15" 
            OnPageIndexChanging="GridViewCarModel_PageIndexChanging"
            Caption="Модели авто" 
            EmptyDataText="Нет данных" CaptionAlign="Top" PageIndex="0">
            <Columns>
                <asp:BoundField DataField="CarModelId" HeaderText="Код" SortExpression="CarModelId" />
                <asp:BoundField DataField="Name" HeaderText="Название" SortExpression="Name" />
                <asp:BoundField DataField="Description" HeaderText="Описание" SortExpression="Description" />
            </Columns>
            
    </asp:GridView>
        </td>
        <td>
        <strong>Добавить новую модель авто:</strong>
            <br />
            <asp:label runat="server">Название:</asp:label><asp:TextBox ID="TextBoxCarModelName" runat="server"></asp:TextBox>
            <br />
            <asp:label runat="server" ID="label1">Описание:</asp:label><asp:TextBox ID="TextBoxCarModelDescription" runat="server"></asp:TextBox>
            <br />
        </td>
        <td>
            <asp:Button ID="ButtonAddCarModel" runat="server" Text="Добавить" OnClick="ButtonAddCarModel_Click" />

        </td>
</tr>
</table>
    </asp:Content>
