<%@ Page Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Cars.aspx.cs" Inherits="lab7.Cars" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
        <br />
<table border="0">
    <tr>
    <td>
    <asp:Label ID="LabelFindCar" runat="server" Text="Label">Автомобиль</asp:Label><asp:TextBox ID="TextBoxFindCar" runat="server"></asp:TextBox>
        <asp:Button ID="ButtonFindCar" runat="server" Text="Найти" OnClick="ButtonFindCar_Click" />
    <br />        
        <asp:GridView ID="GridViewCar" runat="server" AutoGenerateColumns="False"
            AllowPaging="True" 
            AutoGenerateDeleteButton="True" 
            AutoGenerateEditButton="True" 
            OnRowCancelingEdit="GridViewCar_RowCancelingEdit" 
            OnRowDeleting="GridViewCar_RowDeleting" 
            OnRowEditing="GridViewCar_RowEditing" 
            OnRowUpdating="GridViewCar_RowUpdating" PageSize="15" 
            OnPageIndexChanging="GridViewCar_PageIndexChanging"
            Caption="Список автомобилей" 
            EmptyDataText="Нет данных" CaptionAlign="Top" PageIndex="0">
            <Columns>
                <asp:BoundField DataField="CarId" HeaderText="Код" SortExpression="CarId" />

                <asp:BoundField DataField="RegNum" HeaderText="Рег.номер" SortExpression="RegNum" />
                <asp:BoundField DataField="VINcode" HeaderText="Номер VIN" SortExpression="VINcode" />
                <asp:BoundField DataField="EngineNum" HeaderText="Номер двигателя" SortExpression="EngineNum" />
                <asp:BoundField DataField="Price" HeaderText="Цена" SortExpression="Price" />
                <asp:BoundField DataField="RentalPrice" HeaderText="Цена аренды" SortExpression="RentalPrice" />
                <asp:BoundField DataField="IssueDate" HeaderText="Дата выпуска" SortExpression="IssueDate" />
                <asp:BoundField DataField="Specs" HeaderText="Характеристики" SortExpression="Specs" />
                <asp:BoundField DataField="TechnicalMaintenanceDate" HeaderText="Дата ТО" SortExpression="TechnicalMaintenanceDate" />
                <asp:BoundField DataField="SpecMark" HeaderText="Особая метка" SortExpression="SpecMark" />
                <asp:BoundField DataField="ReturnMark" HeaderText="Метка возврата" SortExpression="ReturnMark" />

                <asp:TemplateField HeaderText="Модель автомобиля" SortExpression="CarModelId">
                    <EditItemTemplate>
                        <asp:DropDownList ID="CarModelIdDropDownList" runat="server" DataSourceID="SqlDataSourceCarModel" DataTextField="Name" DataValueField="CarModelId" SelectedValue='<%# Bind("CarModelId") %>'>
                        </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate>
                     <asp:Label ID="CarModelId" runat="server"  Text='<%# Eval("CarModel.Name") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>
                
                <asp:TemplateField HeaderText="Сотрудник" SortExpression="EmployeeId">
                    <EditItemTemplate>
                        <asp:DropDownList ID="EmployeeIdDropDownList" runat="server" DataSourceID="SqlDataSourceEmployee" DataTextField="Name" DataValueField="EmployeeId" SelectedValue='<%# Bind("EmployeeId") %>'>
                        </asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate>
                    <asp:Label ID="EmployeeId" runat="server"  Text='<%# Eval("Employee.Name") %>'></asp:Label>
                    </ItemTemplate>
                </asp:TemplateField>



            </Columns>
            
    </asp:GridView>
        </td>
        <td>
        <strong>Добавить новое авто:</strong>
            <br/>
            <asp:label runat="server">Рег.номер:</asp:label><asp:TextBox ID="TextBoxCarRegNum" runat="server"></asp:TextBox>
            <br />
            <asp:label runat="server">Номер VIN:</asp:label><asp:TextBox ID="TextBoxCarVINCode" runat="server"></asp:TextBox>
            <br />
            <asp:label runat="server">Номер двигателя:</asp:label><asp:TextBox ID="TextBoxCarEngineNum" runat="server"></asp:TextBox>
            <br />
            <asp:label runat="server">Цена:</asp:label><asp:TextBox ID="TextBoxCarPrice" runat="server"></asp:TextBox>
            <br />
            <asp:label runat="server">Цена аренды:</asp:label><asp:TextBox ID="TextBoxCarRentalPrice" runat="server"></asp:TextBox>
            <br />
            <asp:label runat="server">Дата выпуска:</asp:label><asp:TextBox ID="TextBoxCarIssueDate" runat="server"></asp:TextBox>
            <br />
            <asp:label runat="server">Характеристики:</asp:label><asp:TextBox ID="TextBoxCarSpecs" runat="server"></asp:TextBox>
            <br />
            <asp:label runat="server">Дата ТО:</asp:label><asp:TextBox ID="TextBoxCarTechnicalMaintenanceDate" runat="server"></asp:TextBox>
            <br />
            <asp:label runat="server">Особая метка:</asp:label><asp:TextBox ID="TextBoxCarSpecMark" runat="server"></asp:TextBox>
            <br />
            <asp:label runat="server">Метка возврата:</asp:label><asp:TextBox ID="TextBoxCarReturnMark" runat="server" ></asp:TextBox>
            <br />
             
            <asp:label runat="server">Сотрудник</asp:label>
            <asp:DropDownList ID="EmployeeDropDownList" DataSourceID="SqlDataSourceEmployee" DataValueField="EmployeeId" DataTextField="Name" runat="server"></asp:DropDownList>
           
            <br />
            <asp:label runat="server">Модель авто</asp:label>
            <asp:DropDownList ID="CarModelDropDownList" DataSourceID="SqlDataSourceCarModel" DataValueField="CarModelId" DataTextField="Name" runat="server"></asp:DropDownList>
            <br />
            <asp:Button ID="ButtonAddCar" runat="server" Text="Добавить" OnClick="ButtonAddCar_Click" />
        </td>   
</tr>
</table>
    <asp:SqlDataSource ID="SqlDataSourceCarModel" runat="server" 
        ConnectionString="<%$ ConnectionStrings:CarSharingConnectionString %>" 
        SelectCommand="SELECT [CarModelId], [Name] FROM [CarModels]">
    </asp:SqlDataSource>
    <asp:SqlDataSource ID="SqlDataSourceEmployee" runat="server" 
        ConnectionString="<%$ ConnectionStrings:CarSharingConnectionString %>" 
        SelectCommand="SELECT [EmployeeId], [Name] FROM [Employees]">
    </asp:SqlDataSource>
    </asp:Content>
